stages:
  - trigger_jenkins

trigger_jenkins_job:
  stage: trigger_jenkins
  script:
    - echo "Triggering Jenkins pipeline..."
    - curl -X POST "http://admin:1185d90d52dbdf516a3a0d5ac9ae4abf22@192.168.230.99:8080/job/Lab_iap491/job/g40_sep490_fal24_Project/buildWithParameters?GIT_BRANCH=$CI_COMMIT_REF_NAME"

